name: Update Profile Stats

on: 
  schedule:
    # 每天UTC时间0点自动运行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - master

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit and push
        run: |
          git config --global user.name "dingdangmaoup"
          git config --global user.email "dingdangmaoup@gmail.com"
          git add .
          git commit -m "Update profile stats"
          git push
